# Generated by Django 3.2.11 on 2022-01-23 18:42

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogarticle_blogcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(to='blog.BlogCategory'),
        ),
    ]
